# Generated by Django 4.1.4 on 2023-10-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appResume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='message',
        ),
    ]
